[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "amethyst"
version = "0.0.1"
description = ""
dependencies = ["rdkit ==2023.3.3"]

[project.optional-dependencies]
dev = ["pytest ==7.4.2"]
